// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uklgjgytlymlifadsjmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbGdqZ3l0bHltbGlmYWRzam13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjA4MzgsImV4cCI6MjA2NDU5NjgzOH0.WLPBAgc-k1yhsOFZ_lZVWnmo5fKKqpXj3hO54x8fICg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);